### ISSUE TITLE
Yakindu: passage de paramètres réels dans l'asservissement

### ISSUE THREAD

**Issue by laguiche** [CRLG/GROSBOT_MBED#18]
Les fonctions d'asservissement dans le modèle Yakindu de la stratégie, n'acceptent pas les paramètres en flottant (cast automatique en double au lieu de float)

**Comment by NicoFarmer** [comment]
Dans le paramètre de la fonction, utiliser le "f" à côté des valeurs numériques pour forcer le type en float.
Exemple : "12.34f'

**Comment by NicoFarmer** [comment]
Idem pour l'utilisation des constantes : PI/2.0f
