### ISSUE TITLE
Remplacement stratégie Yakindu 

### ISSUE THREAD

**Issue by laguiche** [CRLG/GROSBOT_MBED#30]
Malgré l'apparente facilité de design via l'ihm et de codage automatique,  l'utilisation de Yakindu a montré quelques écueils lors de la coupe 2019. Dans l'idéal il faudrait pouvoir:

- Travailler à plusieurs personnes (pas besoin de merge, et surtout à 3h du mat le dernier jour de la coupe)
- Minimiser le temps de mise en œuvre  (copier, coller, code à la main possible)
- reprendre une stratégie prototypée
- pouvoir tester tout ou partie de la stratégie (soit en simu, soit en réel)
- ne pas avoir de licence à renouveler chaque année
- permettre de générer automatiquement une séquence à partir d'un outil pour intégration dans une stratégie
- maximiser le code commun entre les robots
- une insfrastructure facilement utilisable pour un non spécialiste du codage

Un remplacement de Yakindu par une autre solution permettrait donc de gagner du temps à la coupe pour se concentrer sur d'autres tâches et minimiser les essais et les erreurs.

**Comment by NicoFarmer** [comment]
Suite à la réunion du club du 21/12/2019
Pourquoi on veut changer : 
  - Sponsoring à renouveler chaque année
  - Pas de licence pour tout le monde car licence nominative
  - Merge difficile entre plusieurs modèles 
  - Navigation dans le modèle longue
  - Pour retoucher un petit bout de modèle juste avant le match, c'est long
  - Obligation de re-coder en graphique la mise au point d'une séquence faite avec ActuatorSequencer

Décision : on part sur le proto Yakindu like Nico + ActuatorSeqencer de Stéph pour la génération de code
Présentation de la proposition technique du 21/12/2019
[19-12-2019-Yakindu_Like-Nico.pdf](https://github.com/CRLG/GROSBOT_MBED/files/4007254/19-12-2019-Yakindu_Like-Nico.pdf)

**Comment by NicoFarmer** [comment]
L'architecture proposée en remplacement de Yakindu est nommée **Modelia** pour _Model_ et _IA_

**Comment by NicoFarmer** [comment]
Structure "**Modelia**" mise en place : ticket soldé
